name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
    
      run: | 
          docker docker build -t ${{ env.REGISTRY }}/roweb/sd-all:latest .
          docker push ${{ env.REGISTRY }}/roweb/sd-all:latest
